In [2]:
import numpy as np

# Numpy Array Creation

In [4]:
list1=[10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [5]:
type(list1)

list

In [7]:
arr1=np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [8]:
arr1.data
# Memory address of an array object

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.dtype

dtype('int32')

In [11]:
arr1.astype(float)
# converts int to float

array([10., 20., 30., 40., 50., 60.])

In [12]:
np.arange(0,10)
# Generates numbers between 0 to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,100,10)
# Generates numbers between 0 to 100 with step 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
np.arange(100,10,-10)
# Generates numbers between 0 to 100 with step 10 in descending order

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [18]:
arr3=np.arange(0,10)
arr3.shape
# shape of array 

(10,)

In [19]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr3.size
# size of array

10

In [21]:
arr3.ndim
# Dimension

1

In [22]:
arr3.dtype

dtype('int32')

In [24]:
arr3.itemsize
# Bytes consumed by one element of an array object

4

In [25]:
arr3.nbytes
# Bytes consumed by an array object

40

In [26]:
len(arr3)

10

In [27]:
np.zeros(10)
# Generates an array of zeros with given size

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)
# Generates an array of zeros with given size

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.repeat(10,5)
# Repeates 10 five times an array

array([10, 10, 10, 10, 10])

In [30]:
a=np.array([10,20,30])
np.repeat(a,3)
# Repeats each element in array 'a' thrice

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [31]:
np.random.random(4)
# creates an array of random values

array([0.6367738 , 0.40325113, 0.49929153, 0.9868328 ])

In [32]:
np.random.randint(0,500,10)

array([255, 219,  73, 366, 158, 302, 449, 133, 319, 208])

# Operations on an Array

In [37]:
arr2=np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [38]:
sum(arr2)
# sum of all elements in an array

190

In [39]:
np.cumsum(arr2)
# cumulative sum of an array

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

In [40]:
arr2.min()
# Minimum element in an array

1

In [42]:
arr2.max()
# Maximum element in the array

19

In [43]:
arr2.argmin()
# Returns index of min element in the array

0

In [45]:
arr2.argmax()
# Returns index of min element in the array

18

In [46]:
arr2.mean()
# Returns mean of all elements in the array

10.0

In [51]:
np.median(arr2)
# Returns median of all elements in the array

10.0

In [52]:
np.var(arr2)
# variance

30.0

In [53]:
np.std(arr2)
# Standard Deviation

5.477225575051661

In [56]:
np.percentile(arr2,60)
# Percentile

11.799999999999999

# Operations on 2D Array

In [57]:
A = np.array([[1,2,3,0] , [5,6,7,22] , [10 , 11 , 1 ,13] , [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [58]:
A.sum()
# Sum of all elements in 2D Array

129

In [62]:
np.min(A,axis=0)
# Column wise min values

array([1, 2, 1, 0])

In [63]:
np.min(A,axis=1)
# Row wise min elelments

array([0, 5, 1, 3])

# Reading elements of an array

In [66]:
a = np.array([7,5,3,9,0,2])
a

array([7, 5, 3, 9, 0, 2])

In [67]:
a[0]
# Accessing first element of array

7

In [68]:
a[1:]
# Accessing all elements from index 1

array([5, 3, 9, 0, 2])

In [70]:
a[1:4]
# Accessing elements from index 1 to 4

array([5, 3, 9])

In [72]:
a[-1]
# Accessing last element of the array

2

In [73]:
a[-3:-1]

array([9, 0])